
            name: Deploy to Heroku

            on:
              push:
                branches:
                  - main

            jobs:
              build-and-deploy:
                runs-on: ubuntu-latest

                steps:
                  - name: Checkout code
                    uses: actions/checkout@v3

                  - name: Set up Docker Buildx
                    uses: docker/setup-buildx-action@v2

                  - name: Login to Heroku Container Registry
                    run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

                  - name: Build Docker image
                    run: docker build -t registry.heroku.com/azaboobackergenerate-cac47e40/web .

                  - name: Push Docker image to Heroku
                    run: docker push registry.heroku.com/azaboobackergenerate-cac47e40/web

                  - name: Release app
                    run: |
                      heroku container:release web --app azaboobackergenerate-cac47e40
                    env:
                      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            